version: '3.8'

services:
  db:
    image: postgres:15
    container_name: translator-db
    environment:
      POSTGRES_DB: translator_db
      POSTGRES_USER: translator_user
      POSTGRES_PASSWORD: 12341234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
